name: tulip
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.2.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - fontconfig=2.14.1
  - freetype=2.10.4
  - glib=2.69.1
  - icu=58.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libxcb=1.15
  - libxml2=2.9.14
  - ncurses=6.4
  - openbabel=3.1.1
  - openssl=1.1.1w
  - pcre=8.45
  - pip=22.3.1
  - pixman=0.40.0
  - python=3.7.16
  - python_abi=3.7
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - absl-py==2.0.0
    - asttokens==2.4.0
    - attrs==23.2.0
    - bel-resources==0.0.3
    - biopandas==0.4.1
    - biopython==1.81
    - bioregistry==0.9.62
    - cachetools==5.3.1
    - charset-normalizer==3.3.0
    - click==8.1.7
    - click-plugins==1.1.1
    - colorama==0.4.6
    - curies==0.5.5
    - cycler==0.11.0
    - executing==2.0.0
    - fonttools==4.38.0
    - google-auth==2.23.3
    - google-auth-oauthlib==0.4.6
    - greenlet==3.0.3
    - grpcio==1.59.0
    - humanize==4.6.0
    - icecream==2.1.3
    - idna==3.4
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - joblib==1.3.2
    - jsonschema==4.17.3
    - kiwisolver==1.4.5
    - markdown==3.4.4
    - markupsafe==2.1.3
    - matplotlib==3.5.3
    - more-click==0.1.2
    - more-itertools==9.1.0
    - multisplitby==0.0.1
    - networkx==2.6.3
    - numpy==1.21.6
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - packaging==23.2
    - pandas==1.3.5
    - pickle5==0.0.12
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - pot==0.9.1
    - protobuf==3.20.3
    - psycopg2-binary==2.9.9
    - pyaml==23.5.8
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==1.10.15
    - pygments==2.16.1
    - pyparsing==3.1.1
    - pyrosetta==2022.16+release.839b00f
    - pyrsistent==0.19.3
    - pystow==0.5.4
    - python-dateutil==2.8.2
    - pytrie==0.4.0
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - ratelimit==2.2.1
    - rdkit==2023.3.2
    - requests==2.31.0
    - requests-file==2.0.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - six==1.16.0
    - sortedcontainers==2.4.0
    - sqlalchemy==2.0.29
    - tabulate==0.9.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - torch==1.13.1
    - tqdm==4.66.2
    - typing-extensions==4.7.1
    - urllib3==2.0.6
    - werkzeug==2.2.3
    - zipp==3.15.0
